#!/bin/sh
# Source: https://github.com/iterait/dockerfiles 
# Also push with versioned tag.

TIMESTAMP="$(date -u +%Y-%m-%d)"
docker tag "${IMAGE_NAME}" "${DOCKER_REPO}":"${TIMESTAMP}"
docker push "${DOCKER_REPO}":"${TIMESTAMP}"